name: Deploy Cloudformation Stack - Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_STACK_NAME: ${{ vars.AWS_STACK_NAME }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  cloudformation-update-qa:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.AWS_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS CFN
        run: | 
          aws cloudformation deploy --template-file ./cloudformation/production.yml --stack-name=${{ env.AWS_STACK_NAME }}-qa --no-fail-on-empty-changeset --output text --parameters DomainName=qa.${{ env.DOMAIN_NAME }}
      - name: Get Outputs from Stack
        run: |
          aws cloudformation describe-stacks --stack-name=${{ env.AWS_STACK_NAME }}-qa --output table
  cloudformation-update-stage:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.AWS_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS CFN
        run: | 
          aws cloudformation deploy --template-file ./cloudformation/production.yml --stack-name=${{ env.AWS_STACK_NAME }}-stage --no-fail-on-empty-changeset --output text --parameters DomainName=stage.${{ env.DOMAIN_NAME }}
      - name: Get Outputs from Stack
        run: |
          aws cloudformation describe-stacks --stack-name=${{ env.AWS_STACK_NAME }}-stage --output table
  cloudformation-update-prod:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.AWS_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS CFN
        run: | 
          aws cloudformation deploy --template-file ./cloudformation/production.yml --stack-name=${{ env.AWS_STACK_NAME }} --no-fail-on-empty-changeset --output text --parameters DomainName=qa.${{ env.DOMAIN_NAME }}
      - name: Get Outputs from Stack
        run: |
          aws cloudformation describe-stacks --stack-name=${{ env.AWS_STACK_NAME }} --output table
