name: Delete Cloudformation Preview Stack

on:
  pull_request:
    types:
      - "closed"

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_STACK_NAME: ${{ vars.AWS_STACK_NAME }}

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  set-env:
    name: Set Environment
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit
  cloudformation-delete:
    needs: set-env
    runs-on: ubuntu-latest
    name: Delete CFN Stack
    steps: 
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.AWS_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: ${{ needs.set-env.outputs.aws_session_name }}
          aws-region: ${{ env.AWS_REGION }}
      - id: query_bucket
        name: Get S3 Bucket Name
        run: |
          echo "::set-output name=BucketName::$(aws cloudformation describe-stacks --stack-name ${{ needs.set-env.outputs.aws_stack_name }} --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)"
      - name: Delete S3 Bucket Objects
        run: |
          aws s3 rm s3://${{ steps.query_bucket.outputs.BucketName }} --recursive
      - name: Delete AWS CFN Stack
        run: | 
          aws cloudformation delete-stack --stack-name=${{ needs.set-env.outputs.aws_stack_name }}
    