name: Deploy Cloudformation Stack

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_STACK_NAME: ${{ secrets.AWS_STACK_NAME }}

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  # changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     cfn: ${{ steps.changes.outputs.cfn }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dorny/paths-filter@v2
  #       id: changes
  #       with:
  #         filters: |
  #           cfn:
  #             - 'cloudformation/**'
  #             - '.github/workflows/cfn-sync.yml'
  
  cloudformation-update:
    # needs: changes
    # if: ${{ needs.changes.outputs.cfn == 'true' }}
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.AWS_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS CFN
        run: | 
          aws cloudformation deploy --template-file ./cloudformation/formation.yml --stack-name=${{ env.AWS_STACK_NAME }} --no-fail-on-empty-changeset --output text
      - name: Get Outputs from Stack
        run: |
          aws cloudformation describe-stacks --stack-name=${{ env.AWS_STACK_NAME }} --output text
