name: Setup Environment - Preview

on: [workflow_call]

permissions:
  contents: read

env:
  AWS_STACK_NAME: ${{ secrets.AWS_STACK_NAME }}

jobs:
  setup_env:
    name: Setup Preview Job Environment
    runs-on: ubuntu-latest
    outputs:
      aws_session_name: GitHub_to_AWS_via_FederatedOIDC_Preview_${{ steps.set-env.outputs.sha_short }}
      aws_stack_name: ${{ env.AWS_STACK_NAME }}-${{ steps.set-env-outputs.ref_name_replaced }}
    steps:
      - uses: actions/checkout@v3
      - id: find-pull-request
        uses: jwalton/gh-find-current-pr@v1
        with:
          state: all
      - id: set-env
        name: Update Environment
        run: |
          echo "ref_name_replaced=$(echo "refs/pull/${{ steps.find-pull-request.outputs.number }}/merge" | tr / -)" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
